// Generated by CoffeeScript 1.7.1
var root, toClass, typeOf;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

typeOf = function(obj) {
  var getClass;
  if (obj === null) {
    return "[object Null]";
  }
  if (obj === void 0 || typeof obj === "undefined") {
    return "[object Undefined]";
  }
  return getClass = toClass(obj);
};

toClass = function(obj) {
  var str;
  str = Object.prototype.toString.call(obj);
  switch (str) {
    case "[object Function]":
      return (function(obj) {
        var class_name;
        class_name = obj.__class__ || obj.name || "Annonymous";
        return "[class " + class_name + "]";
      })(obj);
    case "[object Object]":
      return (function(obj) {
        var name;
        name = obj.constructor.name || "Annonymous";
        return "[object " + name + "]";
      })(obj);
    default:
      return str;
  }
};

module.exports = typeOf;
